site_name: CET-Docs

theme:
  name: material
  logo: img/logo.svg
  favicon: img/logo.svg
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
    - content.code.copy
    - content.code.select
  icon:
  previous: fontawesome/solid/angle-left
  next: fontawesome/solid/angle-right
font:
  text: Roboto
palette:
# Palette toggle for dark mode
  - scheme: slate
    primary: black
    accent: deep purple
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
# Palette toggle for light mode
  - scheme: default
    primary: grey
    accent: blue grey
    toggle:
      icon: material/brightness-7 
      name: Switch to dark mode