---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "CET-NETWORK"
subtitle: "Administração de Redes e Sistemas"
logo: "logo.svg"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#0d04034" #"#3367d6"
    highlight-secondary: "#4d0a03" #"#4285f4"
    highlight-hover: "#111" #"#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
message:
  #url: https://b4bz.io
  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  title: "CET-NETWORK"
  icon: "fa fa-solid fa-skull-crossbones"
  content: "Sebenta. <br /> Find more information on <a href='https://paulo-godinho.soundworks.live'>Paulo Godinho</a>"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Referencial"
    icon: "fas fa-solid fa-house-user"
    url: "https://catalogo.anqep.gov.pt/qualificacoesDetalhe/46"
    target: "_blank" # optional html a tag target attribute
  - name: "Cockpit"
    icon: "fas fa-gear fa-spin fa-spin-reverse"
    url: "https://cockpit-project.org"
    target: "_blank" # optional html a tag target attribute
  - name: "Webmin"
    icon: "fas fa-solid fa-user-gear"
    url: "https://webmin.com"
    target: "_blank" # optional html a tag target attribute
  - name: "Router"
    icon: "fas fa-network-wired"
    url: "https://www.routerpasswords.com"
    target: "_blank" # optional html a tag target attribute
  - name: "Printer"
    icon: "fas fa-print"
    url: "https://www.cups.org"
    target: "_blank" # optional html a tag target attribute
  - name: "Scanner"
    icon: "fas fa-barcode"
    url: "https://github.com/sbs20/scanserv"
    target: "_blank" # optional html a tag target attribute
  - name: "GitHub"
    icon: "fab fa-github"
    url: "https://github.com/"
    target: "_blank" # optional html a tag target attribute
  - name: "Wiki"
    icon: "fas fa-book"
    url: "https://www.wikipedia.org/"
    target: "_blank" # optional html a tag target attribute
  - name: "Contribute"
    icon: "fab fa-github"
    url: "https://github.com/bastienwirtz/homer"
    target: "_blank" # optional html a tag target attribute
  - name: "PI"
    icon: "fab fa-raspberry-pi"
    url: "#pi"

  # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:
  #- name: "another page!"
  #  icon: "fas fa-file-alt"
  #  url: "#additional-page"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Tools"
    icon: "fa-solid fa-screwdriver-wrench"
    items:
      - name: "VSCode"
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Visual_Studio_Code_1.35_icon.svg/2048px-Visual_Studio_Code_1.35_icon.svg.png"
        subtitle: "Live Coding"
        tag: "vscode"
        url: "https://vscode.dev/"
        target: "_blank" # optional html a tag target attribute
      - name: "CPanel"
        logo: "assets/tools/contabo.png"
        subtitle: "Contabo web space."
        tag: "cpanel"
        keywords: "web space manager"
        url: "https://m14061.contabo.net:2083"
        target: "_blank" # optional html a tag target attribute
      - name: "SoundWorks Live!"
        logo: "assets/tools/logo.svg"
        subtitle: "Radio playout manager"
        tag: "radio"
        url: "https://soundworks.live/login"
        target: "_blank" # optional html a tag target attribute
      - name: "ListenBrainz"
        logo: "https://listenbrainz.org/static/img/listenbrainz_logo_icon.svg"
        subtitle: "Recent Listens"
        tag: "musicbrainz"
        url: "https://listenbrainz.org/user/LordFader/"
        target: "_blank" # optional html a tag target attribute
  ##############################################################################################################
  - name: "Applications"
    icon: "fas fa-cloud"
    items:
      - name: "Pi-Hole"
        logo: "assets/tools/pi-hole.svg"
        subtitle: "Network-wide Ad Blocking"
        tag: "app"
        keywords: "pi"
        url: "http://lf-pi-1.home.arpa/admin/login.php"
        target: "_blank"
      - name: "LF-NAS"
        logo: "assets/tools/nas.png"
        subtitle: "NAS"
        tag: "nas"
        url: "http://lordfader-nas:8080/"
        target: "_blank" # optional html a tag target attribute
      - name: "Plex"
        logo: "assets/tools/plex-logo.svg"
        subtitle: "Media Player"
        tag: "app"
        url: "http://lf-pi-0.home.arpa:32400"
        target: "_blank" # optional html a tag target attribute
  ###################################################################
  - name: "interesting links"
    icon: "fas fa-solid fa-arrow-up-right-from-square"
    items:
      - name: "Buy me a coffee !"
        subtitle: "If you want to support me, buy me a coffee "
        tag: "tip me"
        logo: "https://www.buymeacoffee.com/assets/img/guidelines/logo-mark-1.svg"
        url: "https://www.buymeacoffee.com/pauloGod"
      - name: "r/selfhosted"
        icon: "fa-brands fa-reddit-alien"
        subtitle: "Bookmark example"
        tag: "reddit"
        url: "https://www.reddit.com/r/selfhosted/"
        target: "_blank"
      - name: "Awesome selfhosted"
        icon: "fa-brands fa-github-alt"
        subtitle: "Another application"
        tag: "awesome-list"
        url: "https://github.com/awesome-selfhosted/awesome-selfhosted"
        target: "_blank" # optional html a tag target attribute
